/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SessionRouteImport } from './routes/session'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MorningRouteImport } from './routes/morning'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as EveningRouteImport } from './routes/evening'
import { Route as CrisisRouteImport } from './routes/crisis'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BranchIdRouteImport } from './routes/branch.$id'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'

const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MorningRoute = MorningRouteImport.update({
  id: '/morning',
  path: '/morning',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const EveningRoute = EveningRouteImport.update({
  id: '/evening',
  path: '/evening',
  getParentRoute: () => rootRouteImport,
} as any)
const CrisisRoute = CrisisRouteImport.update({
  id: '/crisis',
  path: '/crisis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchIdRoute = BranchIdRouteImport.update({
  id: '/branch/$id',
  path: '/branch/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crisis': typeof CrisisRoute
  '/evening': typeof EveningRoute
  '/library': typeof LibraryRoute
  '/morning': typeof MorningRoute
  '/profile': typeof ProfileRoute
  '/session': typeof SessionRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/branch/$id': typeof BranchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crisis': typeof CrisisRoute
  '/evening': typeof EveningRoute
  '/library': typeof LibraryRoute
  '/morning': typeof MorningRoute
  '/profile': typeof ProfileRoute
  '/session': typeof SessionRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/branch/$id': typeof BranchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crisis': typeof CrisisRoute
  '/evening': typeof EveningRoute
  '/library': typeof LibraryRoute
  '/morning': typeof MorningRoute
  '/profile': typeof ProfileRoute
  '/session': typeof SessionRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/branch/$id': typeof BranchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crisis'
    | '/evening'
    | '/library'
    | '/morning'
    | '/profile'
    | '/session'
    | '/api/transcribe'
    | '/api/tts'
    | '/branch/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crisis'
    | '/evening'
    | '/library'
    | '/morning'
    | '/profile'
    | '/session'
    | '/api/transcribe'
    | '/api/tts'
    | '/branch/$id'
  id:
    | '__root__'
    | '/'
    | '/crisis'
    | '/evening'
    | '/library'
    | '/morning'
    | '/profile'
    | '/session'
    | '/api/transcribe'
    | '/api/tts'
    | '/branch/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrisisRoute: typeof CrisisRoute
  EveningRoute: typeof EveningRoute
  LibraryRoute: typeof LibraryRoute
  MorningRoute: typeof MorningRoute
  ProfileRoute: typeof ProfileRoute
  SessionRoute: typeof SessionRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiTtsRoute: typeof ApiTtsRoute
  BranchIdRoute: typeof BranchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/morning': {
      id: '/morning'
      path: '/morning'
      fullPath: '/morning'
      preLoaderRoute: typeof MorningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evening': {
      id: '/evening'
      path: '/evening'
      fullPath: '/evening'
      preLoaderRoute: typeof EveningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crisis': {
      id: '/crisis'
      path: '/crisis'
      fullPath: '/crisis'
      preLoaderRoute: typeof CrisisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch/$id': {
      id: '/branch/$id'
      path: '/branch/$id'
      fullPath: '/branch/$id'
      preLoaderRoute: typeof BranchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrisisRoute: CrisisRoute,
  EveningRoute: EveningRoute,
  LibraryRoute: LibraryRoute,
  MorningRoute: MorningRoute,
  ProfileRoute: ProfileRoute,
  SessionRoute: SessionRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiTtsRoute: ApiTtsRoute,
  BranchIdRoute: BranchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
