/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SessionRouteImport } from './routes/session'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MorningRouteImport } from './routes/morning'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as EveningRouteImport } from './routes/evening'
import { Route as IndexRouteImport } from './routes/index'

const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MorningRoute = MorningRouteImport.update({
  id: '/morning',
  path: '/morning',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const EveningRoute = EveningRouteImport.update({
  id: '/evening',
  path: '/evening',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evening': typeof EveningRoute
  '/library': typeof LibraryRoute
  '/morning': typeof MorningRoute
  '/profile': typeof ProfileRoute
  '/session': typeof SessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evening': typeof EveningRoute
  '/library': typeof LibraryRoute
  '/morning': typeof MorningRoute
  '/profile': typeof ProfileRoute
  '/session': typeof SessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evening': typeof EveningRoute
  '/library': typeof LibraryRoute
  '/morning': typeof MorningRoute
  '/profile': typeof ProfileRoute
  '/session': typeof SessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/evening'
    | '/library'
    | '/morning'
    | '/profile'
    | '/session'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/evening' | '/library' | '/morning' | '/profile' | '/session'
  id:
    | '__root__'
    | '/'
    | '/evening'
    | '/library'
    | '/morning'
    | '/profile'
    | '/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EveningRoute: typeof EveningRoute
  LibraryRoute: typeof LibraryRoute
  MorningRoute: typeof MorningRoute
  ProfileRoute: typeof ProfileRoute
  SessionRoute: typeof SessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/morning': {
      id: '/morning'
      path: '/morning'
      fullPath: '/morning'
      preLoaderRoute: typeof MorningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evening': {
      id: '/evening'
      path: '/evening'
      fullPath: '/evening'
      preLoaderRoute: typeof EveningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EveningRoute: EveningRoute,
  LibraryRoute: LibraryRoute,
  MorningRoute: MorningRoute,
  ProfileRoute: ProfileRoute,
  SessionRoute: SessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
